### ISSUE TITLE
회원가입 API 호출시 네트워크 오류 발생 

### ISSUE THREAD

**Issue by Hira-Yuki** [relayfairytale/Front#3]
CORS 정책으로 인해 발생하는 오류 
백과 프론트 도메인이 달라 발생하는 문제로 서버에서 문제 해결 필요.

@BYUNCHANGILL 
@JuhyuckHong

**Comment by JuhyuckHong** [comment]
@Hira-Yuki http://miniproject.ap-northeast-2.elasticbeanstalk.com/stories
http://localhost:3000 에 대해서 CORS allow 했습니다. 
나중에 FE 배포 시 해당 서버 주소는 그때 allow 하겠습니다.
![image](https://github.com/relayfairytale/Front/assets/128202933/a8851bac-da3b-4e0d-9b4e-d6d37c6990b0)
![image](https://github.com/relayfairytale/Front/assets/128202933/84a22e2a-c760-4d96-9b8c-e381cc6fcf85)
